---
- name: Install elasticsearch
  hosts: elasticsearch
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Copy elasticsearch 7.14.1
      copy:
        src: /home/nik/Diplom/elk/elasticsearch-7.17.9-amd64.deb
        dest: /home/ans/

    - name: Install elasticsearch
      apt:
        deb: /home/ans/elasticsearch-7.17.9-amd64.deb

    - name: Copy config file for elasticsearch
      copy:
        src: /home/nik/Diplom/elk/files/elasticsearch.yml
        dest: /etc/elasticsearch
        mode: 0660
        owner: root
        group: elasticsearch

    - name: Systemctl daemon reload
      systemd:
        daemon_reload: true
        name: elasticsearch.service
        state: started

    - name: Systemctl enable elasticsearch
      systemd:
        name: elasticsearch.service
        state: restarted
