---
- name: Install kibana
  hosts: kibana
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Install kibana
      shell: |
        cp /home/nik/Diplom/elk/kibana-7.17.9-amd64.deb /home
        cp /home/nik/Diplom/elk/kibana-7.17.9-amd64.deb.sha512 /home
        shasum -a 512 kibana-7.17.9-amd64.deb
        sudo dpkg -i kibana-7.17.9-amd64.deb
        apt install kibana
        systemctl daemon-reload
        systemctl enable kibana.service
        systemctl start kibana.service

    - name: Copy config file for kibana
      copy:
        src: /home/nik/Diplom/elk/files/kibana.yml
        dest: /etc/kibana
        mode: 0644
        owner: root
        group: root

    - name: Systemctl restart elasticsearch
      systemd:
        name: kibana.service
        state: restarted
