---
- name: Install elasticsearch
  hosts: elastic
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: "Add gpg-key"
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add
        echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list
        apt update && apt-get install elasticsearch

    - name: Copy config file for elasticsearch
      copy:
        src: /home/nik/Diplom/elk/files/elasticsearch.yml
        dest: /etc/elasticsearch
        mode: 0660
        owner: root
        group: elasticsearch

    - name: Systemctl daemon reload
      systemd:
        daemon_reload: true
        name: elasticsearch.service
        state: started

    - name: Systemctl enable elasticsearch
      systemd:
        name: elasticsearch.service
        state: restarted

