---
- hosts: elastic, kibana
  become: true
  vars:
   zabbix_server_ip: 10.4.0.20
  
  tasks:
  - name: "Install required packages"
    apt:
     name: ["zabbix-agent"]
     state: present
     
  - name: "Copy Zabbix Agent config"
    template:
      src: ./templates/zabbix_agent.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
      owner: root
      group: sudo
      mode: '0644'

  - name: "Restart Zabbix Agent"
    service:
      name: zabbix-agent
      state: restarted
