---
- name: Install Zabbix Agent
  hosts: elastic, kibana
  become: true

  tasks:
    - name: Copy Zabbix Agent config template
      template:
        src: templates/zabbix_agent.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: zabbix
        group: zabbix
      notify: Restart Zabbix Agent

    - name: Install Zabbix Agent package
      apt:
        name: zabbix-agent
        update_cache: yes
        state: latest

  handlers:
    - name: Restart Zabbix Agent
      service:
        name: zabbix-agent
        state: restarted
