---
- hosts: "nginx"
  become:
    true

  tasks:
  - name: "Install nginx"
    apt:
     name: nginx
     update_cache: yes
     state: present

  - name: "copy websie file"
    copy:
      src: /home/nik/Diplom/index.html
      dest: /var/www/html/index.html
      owner: root
      group: sudo
      mode: "0644"

  - name: "Restart Nginx"
    service:
      name: nginx
      state: restarted
